import type { Metadata } from "next";
import {Rajdhani} from "next/font/google";
import "./globals.css";
import {Header} from "@/components/Header";
import {Footer} from "@/components/Footer";
import {NextFont, NextFontWithVariable} from "next/dist/compiled/@next/font";
import {WixClientContextProvider} from "@/context/wixContext";
import {Toaster} from "@/components/ui/toaster";

const rajdhani:NextFontWithVariable = Rajdhani({
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700'],
    variable: '--font-rajdhani',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rajdhani.variable}>
      <WixClientContextProvider>
          <Header/>
          {children}
          <Toaster />
          <Footer/>
      </WixClientContextProvider>
      </body>
    </html>
  );
}
